services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    env_file:
<<<<<<< HEAD
      - ${BASE_DIR}.env
=======
      - ${NERON_BASE}${NERON_ENV}/.env
>>>>>>> release/1.2.0

    container_name: homeassistant_${NERON_ENV}
    restart: unless-stopped

    privileged: false

    environment:
      TZ: Europe/Paris

    volumes:
      - ${NERON_BASE}${NERON_ENV}/services/homeassistant/config:/config
      - /run/dbus:/run/dbus:ro

    ports:
      - "${HOMEASSISTANT_HTTP}:8123"

    networks:
      - Homebox

networks:
  Homebox:
    name: ${HOMEBOX_NETWORK}
    external: true
