services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    env_file:
      - ${NERON_BASE}.env


    container_name: homeassistant
    restart: unless-stopped

    privileged: false

    environment:
      TZ: Europe/Paris

    volumes:
      - ${NERON_BASE}data/homeassistant/config:/config
      - /run/dbus:/run/dbus:ro

    ports:
      - "${HOMEASSISTANT_HTTP}:8123"

    networks:
      - Homebox

networks:
  Homebox:
    name: ${HOMEBOX_NETWORK}
    external: true